/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentcarproject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author busra
 */
public class AddNewContact extends javax.swing.JFrame {

    /**
     * Creates new form AddNewAddress
     */
    public AddNewContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_close2 = new javax.swing.JLabel();
        jLabel_addressType = new javax.swing.JLabel();
        jTextField_addressType = new javax.swing.JTextField();
        jLabel_descAddress = new javax.swing.JLabel();
        jTextField_descAddress = new javax.swing.JTextField();
        jLabel_telNo = new javax.swing.JLabel();
        jTextField_telNo = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel_district = new javax.swing.JLabel();
        jTextField_district = new javax.swing.JTextField();
        jLabel_postcode = new javax.swing.JLabel();
        jTextField_postcode = new javax.swing.JTextField();
        jLabel_city = new javax.swing.JLabel();
        jTextField_city = new javax.swing.JTextField();
        jLabel_country = new javax.swing.JLabel();
        jTextField_country = new javax.swing.JTextField();
        jButton_addcontact = new javax.swing.JButton();
        jTextField_customerid = new javax.swing.JTextField();
        jLabel_customerid = new javax.swing.JLabel();
        jLabel_contactid = new javax.swing.JLabel();
        jTextField_contactid = new javax.swing.JTextField();
        jButton_listcontact = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_listcontacts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel3.setText("Add Contact Informations to a Customer");

        jLabel_close2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_close2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_close2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_close2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close2.setText("X");
        jLabel_close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close2.setOpaque(true);
        jLabel_close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_close2jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(308, 308, 308)
                .addComponent(jLabel_close2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel_addressType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_addressType.setText("Type of an Address :");

        jTextField_addressType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addressTypeActionPerformed(evt);
            }
        });

        jLabel_descAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_descAddress.setText("Address Description :");

        jLabel_telNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_telNo.setText("Telephone Number :");

        jLabel_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_email.setText("E-Mail :");

        jLabel_district.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_district.setText("District :");

        jLabel_postcode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_postcode.setText("Post Code :");

        jLabel_city.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_city.setText("City :");

        jLabel_country.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_country.setText("Country :");

        jButton_addcontact.setBackground(new java.awt.Color(0, 153, 102));
        jButton_addcontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_addcontact.setForeground(new java.awt.Color(255, 255, 255));
        jButton_addcontact.setText("Add Contact Informations to a Customer");
        jButton_addcontact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_addcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addcontactActionPerformed(evt);
            }
        });

        jLabel_customerid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_customerid.setText("Customer ID :");

        jLabel_contactid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_contactid.setText("Contact ID :");

        jButton_listcontact.setBackground(new java.awt.Color(0, 153, 102));
        jButton_listcontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_listcontact.setForeground(new java.awt.Color(255, 255, 255));
        jButton_listcontact.setText("List Contact Informations");
        jButton_listcontact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_listcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_listcontactActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jTable_listcontacts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Contact ID", "Tel No", "E-Mail", "Type Address", "Address Description", "District", "Post Code", "City", "Country", "Customer ID"
            }
        ));
        jScrollPane1.setViewportView(jTable_listcontacts);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_addcontact)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_city, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_telNo)
                                    .addComponent(jLabel_addressType)
                                    .addComponent(jLabel_email)
                                    .addComponent(jLabel_descAddress)
                                    .addComponent(jLabel_district)
                                    .addComponent(jLabel_postcode)
                                    .addComponent(jLabel_country)
                                    .addComponent(jLabel_customerid)
                                    .addComponent(jLabel_contactid))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jTextField_addressType)
                                                            .addComponent(jTextField_telNo)
                                                            .addComponent(jTextField_email)
                                                            .addComponent(jTextField_descAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jTextField_district, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jTextField_postcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextField_city, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField_country, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_customerid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_contactid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_listcontact)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_contactid)
                            .addComponent(jTextField_contactid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_telNo)
                            .addComponent(jTextField_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_email)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_addressType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_addressType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_descAddress)
                            .addComponent(jTextField_descAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_district)
                            .addComponent(jTextField_district, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_postcode)
                            .addComponent(jTextField_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_city)
                            .addComponent(jTextField_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_country)
                            .addComponent(jTextField_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_customerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_customerid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_addcontact)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_listcontact)
                        .addGap(17, 17, 17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getResult(JTable t, ResultSet s) throws SQLException {

        // first need to get number of columns in the result.
        int rowNum = s.getMetaData().getColumnCount();

        // get the name of each column within the result.
        ArrayList<String> columnNames = new ArrayList<>();
        for (int i = 1; i <= rowNum; i++) {
            columnNames.add(s.getMetaData().getColumnName(i));
        }
        // get the entire results table into an an arraylist of String arrays.
        List<List<String>> rec = new ArrayList<>();
        while (s.next()) {
            List<String> record = new ArrayList<>();
            for (java.lang.String columnName : columnNames) {
                String nextValue = s.getString(columnName);
                record.add(nextValue);
            }
            rec.add(record);
        }
        var columnArray = columnNames.toArray(new String[0]);
        DefaultTableModel model = new DefaultTableModel(columnArray,10);
        t.setEnabled(false);
        t.setModel(model);
        model.setRowCount(0);
        for (int i = 0; i < rec.size(); i++) {
            String [] record = rec.get(i).toArray(new String[0]);
            model.addRow(record);
        }
   }
    
    private void jLabel_close2jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_close2jLabel_closeMouseClicked
        // TODO add your handling code here:
        // close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_close2jLabel_closeMouseClicked

    private void jTextField_addressTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addressTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressTypeActionPerformed

    private void jButton_addcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addcontactActionPerformed
        // TODO add your handling code here:
        //add contacts to a customer
        String idContact = jTextField_contactid.getText();
        String telNoContact = jTextField_telNo.getText();
        String emailContact = jTextField_email.getText();
        String typeAddressContact = jTextField_addressType.getText();
        String addressContact = jTextField_descAddress.getText();
        String districtContact = jTextField_district.getText();
        String postCodeContact = jTextField_postcode.getText();
        String cityAddressContact = jTextField_city.getText();
        String countryAddressContact = jTextField_country.getText();
        String idCustomer = jTextField_customerid.getText();
        
        
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","12345678");
            Statement stmt = con.createStatement();
           stmt.executeUpdate("INSERT INTO `mydb`.`Contact` (`idContact`, `telNoContact`, `emailContact`, `typeAddressContact`, `addressContact`, `districtAddressContact`, `postCodeAddressContact`, `cityAddressContact`, `countryAddressContact`, `Customer_idCustomer`)" + "VALUES ('"+idContact+"', '"+telNoContact+"', '"+emailContact+"', '"+typeAddressContact+"', '"+addressContact+"', '"+districtContact+"', '"+postCodeContact+"', '"+cityAddressContact+"', '"+countryAddressContact+"', '"+idCustomer+"')");

            Statement stmt2 = con.createStatement();
            ResultSet rs2 = stmt2.executeQuery("select * from Contact");
            getResult(jTable_listcontacts,rs2);
            }catch(SQLException e){
            System.out.print(e);
            }
    }//GEN-LAST:event_jButton_addcontactActionPerformed

    private void jButton_listcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_listcontactActionPerformed
        // TODO add your handling code here:
        // list contacts
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","12345678");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select *from Contact");
            getResult(jTable_listcontacts,rs);
            }catch(SQLException e){
            System.out.print(e);
            }
    }//GEN-LAST:event_jButton_listcontactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddNewContact().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addcontact;
    private javax.swing.JButton jButton_listcontact;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_addressType;
    private javax.swing.JLabel jLabel_city;
    private javax.swing.JLabel jLabel_close2;
    private javax.swing.JLabel jLabel_contactid;
    private javax.swing.JLabel jLabel_country;
    private javax.swing.JLabel jLabel_customerid;
    private javax.swing.JLabel jLabel_descAddress;
    private javax.swing.JLabel jLabel_district;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_postcode;
    private javax.swing.JLabel jLabel_telNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_listcontacts;
    private javax.swing.JTextField jTextField_addressType;
    private javax.swing.JTextField jTextField_city;
    private javax.swing.JTextField jTextField_contactid;
    private javax.swing.JTextField jTextField_country;
    private javax.swing.JTextField jTextField_customerid;
    private javax.swing.JTextField jTextField_descAddress;
    private javax.swing.JTextField jTextField_district;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_postcode;
    private javax.swing.JTextField jTextField_telNo;
    // End of variables declaration//GEN-END:variables
}
