/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentcarproject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author busra
 */
public class RentVehicle extends javax.swing.JFrame {

    /**
     * Creates new form RentVehicle
     */
    public RentVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_customerid = new javax.swing.JLabel();
        jTextField_customerid = new javax.swing.JTextField();
        jLabel_vehicleid = new javax.swing.JLabel();
        jTextField_vehicleid = new javax.swing.JTextField();
        jLabel_Rentid = new javax.swing.JLabel();
        jTextField_Rentid = new javax.swing.JTextField();
        jLabel_acqdate = new javax.swing.JLabel();
        jLabel_duedate = new javax.swing.JLabel();
        jButton_rentcar = new javax.swing.JButton();
        jTextField_employeeid = new javax.swing.JTextField();
        jLabel_employeeid = new javax.swing.JLabel();
        jTextField_acqdate = new javax.swing.JTextField();
        jTextField_duedate = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_listrent = new javax.swing.JTable();
        jButton_listrent = new javax.swing.JButton();
        jLabel_employeelogin = new javax.swing.JLabel();
        jTextField_employeelogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("Rent a Vehicle");

        jLabel_close.setBackground(new java.awt.Color(0, 153, 153));
        jLabel_close.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.setOpaque(true);
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addContainerGap(490, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jLabel_customerid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_customerid.setText("Customer ID :");

        jLabel_vehicleid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_vehicleid.setText("Vehicle ID :");

        jLabel_Rentid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Rentid.setText("Rent ID :");

        jLabel_acqdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_acqdate.setText("Acqusition Date :");

        jLabel_duedate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_duedate.setText("Due Date :");

        jButton_rentcar.setBackground(new java.awt.Color(0, 153, 102));
        jButton_rentcar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_rentcar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rentcar.setText("Rent the Car");
        jButton_rentcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rentcarActionPerformed(evt);
            }
        });

        jLabel_employeeid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_employeeid.setText("Employee ID :");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jTable_listrent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Vehicle ID", "Rent ID", "Acqusition Date", "Due Date", "Employee ID", "Login ID"
            }
        ));
        jScrollPane1.setViewportView(jTable_listrent);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton_listrent.setBackground(new java.awt.Color(0, 153, 102));
        jButton_listrent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_listrent.setForeground(new java.awt.Color(255, 255, 255));
        jButton_listrent.setText("List Rented Cars");
        jButton_listrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_listrentActionPerformed(evt);
            }
        });

        jLabel_employeelogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_employeelogin.setText("Employee Login ID :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Format: YYYY-MM-DD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_listrent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_customerid)
                            .addComponent(jLabel_vehicleid)
                            .addComponent(jLabel_Rentid)
                            .addComponent(jLabel_acqdate)
                            .addComponent(jLabel_duedate)
                            .addComponent(jLabel_employeeid)
                            .addComponent(jLabel_employeelogin)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_rentcar)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_acqdate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Rentid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_vehicleid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_customerid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_employeeid)
                                .addComponent(jTextField_duedate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_employeelogin, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_customerid)
                            .addComponent(jTextField_customerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_vehicleid)
                            .addComponent(jTextField_vehicleid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Rentid)
                            .addComponent(jTextField_Rentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_acqdate)
                            .addComponent(jTextField_acqdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_duedate)
                            .addComponent(jTextField_duedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_employeeid)
                            .addComponent(jTextField_employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_employeelogin)
                            .addComponent(jTextField_employeelogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_rentcar)
                        .addGap(47, 47, 47)
                        .addComponent(jButton_listrent)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getResult(JTable t, ResultSet s) throws SQLException {

        // first need to get number of columns in the result.
        int rowNum = s.getMetaData().getColumnCount();

        // get the name of each column within the result.
        ArrayList<String> columnNames = new ArrayList<>();
        for (int i = 1; i <= rowNum; i++) {
            columnNames.add(s.getMetaData().getColumnName(i));
        }
        // get the entire results table into an an arraylist of String arrays.
        List<List<String>> rec = new ArrayList<>();
        while (s.next()) {
            List<String> record = new ArrayList<>();
            for (java.lang.String columnName : columnNames) {
                String nextValue = s.getString(columnName);
                record.add(nextValue);
            }
            rec.add(record);
        }
        var columnArray = columnNames.toArray(new String[0]);
        DefaultTableModel model = new DefaultTableModel(columnArray,7);
        t.setEnabled(false);
        t.setModel(model);
        model.setRowCount(0);
        for (int i = 0; i < rec.size(); i++) {
            String [] record = rec.get(i).toArray(new String[0]);
            model.addRow(record);
        }
   }
    
    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // TODO add your handling code here:
        // close the form
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jButton_listrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_listrentActionPerformed
        // TODO add your handling code here:
        // list rented cars
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","12345678");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select *from Rent");
            getResult(jTable_listrent,rs);
            }catch(SQLException e){
            System.out.print(e);
            }
    }//GEN-LAST:event_jButton_listrentActionPerformed

    private void jButton_rentcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rentcarActionPerformed
        // TODO add your handling code here:
        //add a car to rent
        String idCustomer = jTextField_customerid.getText();
        String idVehicle = jTextField_vehicleid.getText();
        String idRent = jTextField_Rentid.getText();
        String acqusitionDateRent = jTextField_acqdate.getText();
        String dueDateRent = jTextField_duedate.getText();
        String idEmployee = jTextField_employeeid.getText();
        String idLoginEmployee = jTextField_employeelogin.getText();
        
        
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb","root","12345678");
            Statement stmt = con.createStatement();
           stmt.executeUpdate("INSERT INTO `mydb`.`Rent` (`Customer_idCustomer`, `Vehicle_idVehicle`, `idRent`, `acqusitionDate`, `dueDate`, `Employee_idEmployee`, `Employee_Login_idLogin`)" + "VALUES ('"+idCustomer+"', '"+idVehicle+"', '"+idRent+"', '"+acqusitionDateRent+"', '"+dueDateRent+"', '"+idEmployee+"', '"+idLoginEmployee+"')");

            Statement stmt2 = con.createStatement();
            ResultSet rs2 = stmt2.executeQuery("select * from Rent");
            getResult(jTable_listrent,rs2);
            }catch(SQLException e){
            System.out.print(e);
            }
    }//GEN-LAST:event_jButton_rentcarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RentVehicle().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_listrent;
    private javax.swing.JButton jButton_rentcar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Rentid;
    private javax.swing.JLabel jLabel_acqdate;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_customerid;
    private javax.swing.JLabel jLabel_duedate;
    private javax.swing.JLabel jLabel_employeeid;
    private javax.swing.JLabel jLabel_employeelogin;
    private javax.swing.JLabel jLabel_vehicleid;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_listrent;
    private javax.swing.JTextField jTextField_Rentid;
    private javax.swing.JTextField jTextField_acqdate;
    private javax.swing.JTextField jTextField_customerid;
    private javax.swing.JTextField jTextField_duedate;
    private javax.swing.JTextField jTextField_employeeid;
    private javax.swing.JTextField jTextField_employeelogin;
    private javax.swing.JTextField jTextField_vehicleid;
    // End of variables declaration//GEN-END:variables
}
